#!/usr/bin/env bash
# Bundle index.html / style.css / app.js into a C++ header with three raw-string literals.
# Re-run after editing any asset. Wired into CMake via add_custom_command in src/CMakeLists.txt.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
OUT="$(cd "$SRC/../.." && pwd)/controller/explorer_assets.generated.h"
DELIM="EXPLORER_DELIM"

for f in "$SRC/index.html" "$SRC/style.css" "$SRC/app.js"; do
  if [[ ! -f "$f" ]]; then
    echo "ERROR: missing asset: $f" >&2
    exit 1
  fi
  if grep -q ")$DELIM\"" "$f"; then
    echo "ERROR: asset $f contains the raw-string delimiter ')$DELIM\"'." >&2
    echo "       Pick a different DELIM in regen.sh." >&2
    exit 1
  fi
done

{
  echo "// AUTO-GENERATED by src/extensions/http/static/explorer/regen.sh"
  echo "// DO NOT EDIT BY HAND. Re-run regen.sh after editing the asset files."
  echo "#pragma once"
  echo ""
  printf 'inline constexpr const char* EXPLORER_INDEX_HTML = R"%s(\n' "$DELIM"
  cat "$SRC/index.html"
  printf ')%s";\n' "$DELIM"
  echo ""
  printf 'inline constexpr const char* EXPLORER_STYLE_CSS = R"%s(\n' "$DELIM"
  cat "$SRC/style.css"
  printf ')%s";\n' "$DELIM"
  echo ""
  printf 'inline constexpr const char* EXPLORER_APP_JS = R"%s(\n' "$DELIM"
  cat "$SRC/app.js"
  printf ')%s";\n' "$DELIM"
} > "$OUT"

echo "wrote $OUT"
